name: Cek Akun Aktif V2RayNG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # penting agar bisa push pakai PAT

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd curl jq git

      - name: Cek config aktif & buat output
        run: |
          mkdir -p output/aktif
          > output/aktif/all_aktif.txt
          echo "[]" > output/aktif/all_aktif.json

          while read url; do
            [[ -z "$url" ]] && continue
            echo "Download $url ..."
            tmpfile=$(mktemp)
            curl -s "$url" -o "$tmpfile"

            if grep -qE '^[A-Za-z0-9+/]+=*$' "$tmpfile"; then
              tmp_dec=$(mktemp)
              base64 --decode "$tmpfile" > "$tmp_dec" 2>/dev/null || cp "$tmpfile" "$tmp_dec"
            else
              tmp_dec="$tmpfile"
            fi

            file_name=$(echo $url | awk -F/ '{print $3}').txt
            output_file="output/aktif/$file_name"
            > "$output_file"

            while read line; do
              [[ -z "$line" ]] && continue

              if [[ "$line" == vmess:* ]]; then
                json=$(echo $line | sed 's|^vmess://||' | base64 --decode 2>/dev/null)
                host=$(echo $json | jq -r '.add')
                port=$(echo $json | jq -r '.port')
                id=$(echo $json | jq -r '.id')
                alterId=$(echo $json | jq -r '.aid')
                net=$(echo $json | jq -r '.net')
                type=$(echo $json | jq -r '.type')
                path=$(echo $json | jq -r '.path')
                tls=$(echo $json | jq -r '.tls')
                proto="vmess"
              elif [[ "$line" == vless:* ]]; then
                host=$(echo $line | sed -E 's|vless://[^@]+@([^:]+):([0-9]+).*|\1|')
                port=$(echo $line | sed -E 's|vless://[^@]+@([^:]+):([0-9]+).*|\2|')
                id=$(echo $line | sed -E 's|vless://([^@]+)@.*|\1|')
                proto="vless"
              elif [[ "$line" == trojan:* ]]; then
                host=$(echo $line | sed -E 's|trojan://[^@]+@([^:]+):([0-9]+).*|\1|')
                port=$(echo $line | sed -E 's|trojan://[^@]+@([^:]+):([0-9]+).*|\2|')
                passwd=$(echo $line | sed -E 's|trojan://([^@]+)@.*|\1|')
                proto="trojan"
              elif [[ "$line" == ss:* ]]; then
                ss_dec=$(echo $line | sed 's|ss://||' | base64 --decode 2>/dev/null)
                host=$(echo $ss_dec | cut -d':' -f1)
                port=$(echo $ss_dec | cut -d':' -f2)
                passwd=$(echo $ss_dec | cut -d':' -f3)
                proto="ss"
              else
                host=$(echo $line | cut -d':' -f1)
                port=$(echo $line | cut -d':' -f2)
                proto="unknown"
              fi

              if [[ -n "$host" && -n "$port" ]] && nc -z -w5 $host $port 2>/dev/null; then
                echo "$line" >> "$output_file"
                echo "$line" >> output/aktif/all_aktif.txt

                jq --arg proto "$proto" --arg host "$host" --arg port "$port" \
                   --arg id "${id:-}" --arg alterId "${alterId:-}" \
                   --arg net "${net:-}" --arg type "${type:-}" --arg path "${path:-}" \
                   --arg tls "${tls:-}" --arg passwd "${passwd:-}" \
                   '. += [{"protocol":$proto,"host":$host,"port":$port,"id":$id,"alterId":$alterId,"net":$net,"type":$type,"path":$path,"tls":$tls,"passwd":$passwd}]' \
                   output/aktif/all_aktif.json > output/aktif/tmp.json && mv output/aktif/tmp.json output/aktif/all_aktif.json
              fi

            done < "$tmp_dec"

            rm "$tmpfile" || true
            [[ "$tmp_dec" != "$tmpfile" ]] && rm "$tmp_dec" || true

          done < sub_urls.txt

      - name: Push hasil ke repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # PAT harus disimpan di Secrets repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/aktif/
          git commit -m "Update akun aktif"
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }} HEAD:main
