name: Cek Semua Config Aktif & Master TXT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd curl jq

      - name: Cek config aktif dan buat master TXT
        run: |
          mkdir -p output/aktif
          > output/aktif/all_aktif.txt

          while read url; do
            [[ -z "$url" ]] && continue
            echo "Download $url ..."
            tmpfile=$(mktemp)
            curl -s "$url" -o "$tmpfile"

            # Decode base64 jika perlu
            if grep -qE '^[A-Za-z0-9+/]+=*$' "$tmpfile"; then
              tmp_dec=$(mktemp)
              base64 --decode "$tmpfile" > "$tmp_dec" 2>/dev/null || cp "$tmpfile" "$tmp_dec"
            else
              tmp_dec="$tmpfile"
            fi

            # Nama file output per URL, berekstensi .txt
            file_name=$(echo $url | awk -F/ '{print $3}').txt
            output_file="output/aktif/$file_name"
            > "$output_file"

            while read line; do
              [[ -z "$line" ]] && continue

              # Parsing VMess/VLess/Trojan/SS
              if [[ "$line" == vmess:* ]]; then
                json=$(echo $line | sed 's|^vmess://||' | base64 --decode 2>/dev/null)
                host=$(echo $json | jq -r '.add')
                port=$(echo $json | jq -r '.port')
              elif [[ "$line" == vless:* ]]; then
                host=$(echo $line | sed -E 's|vless://[^@]+@([^:]+):([0-9]+).*|\1|')
                port=$(echo $line | sed -E 's|vless://[^@]+@([^:]+):([0-9]+).*|\2|')
              elif [[ "$line" == trojan:* ]]; then
                host=$(echo $line | sed -E 's|trojan://[^@]+@([^:]+):([0-9]+).*|\1|')
                port=$(echo $line | sed -E 's|trojan://[^@]+@([^:]+):([0-9]+).*|\2|')
              elif [[ "$line" == ss:* ]]; then
                ss_dec=$(echo $line | sed 's|ss://||' | base64 --decode 2>/dev/null)
                host=$(echo $ss_dec | cut -d':' -f1)
                port=$(echo $ss_dec | cut -d':' -f2)
              else
                host=$(echo $line | cut -d':' -f1)
                port=$(echo $line | cut -d':' -f2)
              fi

              # Cek koneksi TCP
              if [[ -n "$host" && -n "$port" ]] && nc -z -w5 $host $port 2>/dev/null; then
                echo "$line" >> "$output_file"
                echo "$line" >> output/aktif/all_aktif.txt
              fi

            done < "$tmp_dec"

            echo "$file_name: $(wc -l < "$output_file") aktif"
            rm "$tmpfile" || true
            [[ "$tmp_dec" != "$tmpfile" ]] && rm "$tmp_dec" || true

          done < sub_urls.txt

      - name: Commit hasil aktif
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output/aktif/
          git commit -m "Update semua akun aktif dan all_aktif.txt" || echo "No changes"
          git push
